[package]
name = "verify_orig"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "verify_orig"
test = false

# anchor: wNRjWYxF
[dependencies]
postgres = { version = "*", features = ["with-serde_json-1", "with-chrono-0_4"] }
serde_json = "1.0"
chrono = "0.4"
